meta_product_name: "VerSe"
meta_title: "VerSe · Find Your Sports Buddy"
meta_description: "VerSe is a platform that helps you find your sports buddy. Whether you are looking for a tennis partner, a running buddy or a group to play basketball with, VerSe is the place to be."
meta_image: "VerSe.png"
twitter_account: "@product_twitter_account"
